.github/workflows/main.yml

On push to main branch; automatic jest test is run

Created a main.yml

---

Controllers/Authenticationcontrollers/Login.js
Database/Database.js
Routes/Authenticationroutes.js
Tests/Controllers/Authenticationcontrollers/Login.test.js
package-lock.json
package.json
server.js

Created folders for AuthenticationControllers and a Route for Authentication - where login endpoint is placed.
Imported it all to server and between eachother.
Exported a test-db from my own account to test exports, imports and fetching data. Imported this to test-file.
Created 3 test for /auth/login-endpoint, successful login, token-attachment and failed login.

Darkshiira

---

.github/workflows/main.yml

Updated main.yml to run tests on pull requests to main and not just on pushes.

added run test on pull requests

---

.github/workflows/main.yml

Updated theyml file

---

Controllers/Feedcontrollers/GetFeed.js

Did some db-query-changes, so that it searches for the followers the user has and then maps the followers different posts to res.send

changed how to find posts from followers from db

---

middleware/checkAuthentication.js

- Switched headers.authorization to cookies.authToken.
- Note: Tests for this one need to be changed to match the new token/cookie

Changed headers to cookie token

---

Controllers/PostControllers/createPost.js

Small change so response is in json

changed to json instead of send

---

Controllers/PostControllers/likePost.js
Routes/PostRoutes.js
Validations/likePostValidation.js

- Created controller for liking/unliking posts.
NOTE: I wanted to make the database query in one row but had issues with $cond since it requires a boolean value. Functionality managed with if/else for now but could be improved later. I've kept the $cond query in comment for now.
- Route for liking/unliking posts.
- Validation for post id

Like posts

---

Controllers/Feedcontrollers/GetFeed.js

changed send to json

---

Controllers/MembersControllers/GetFollows.js
Controllers/MembersControllers/GetMember.js
Controllers/MembersControllers/GetMembers.js
Routes/Membersroute.js
Tests/Controllers/MembersControllers/GetFollows.test.js
Tests/Controllers/MembersControllers/GetMembers.test.js
server.js

Made a Route, a controller and a test for fetching members-endpoint.
Update : made another controller and a test for fetching followers
Update: made another controller for fetching data to member-page

Membersendpoint

---

Controllers/MembersControllers/FollowMember.js

Fixed a wrong name on string

---

Controllers/Authenticationcontrollers/Register.js

profilePic with empty string value is added to each user document att register. Profile picture is set later at user profile after login.

added empty profilePic for Users at register

---

Routes/PostRoutes.js

Added /:id to comment route, my bad

forgot id to comment route, added now

---

Controllers/Feedcontrollers/GetFeed.js

Tiny update so users posts are in feed. Just pushed the user into the already excisting array

Added so usernames posts are in feed

---

Controllers/Feedcontrollers/GetFeed.js

Added sort to feed so the entire feed is displayed in descending order (newest at the top)

Sorted feed to display in descending order

---

Controllers/Feedcontrollers/GetFeed.js
Controllers/MembersControllers/FollowMember.js
Controllers/MembersControllers/GetMember.js
Controllers/MembersControllers/GetUserInfo.js
Validations/followMemberValidation.js
Validations/getUserInfoValidation.js

Put validation outside code to minimize the code inside a document,
removed some unnecessary imports,
refactored one line of code

Validation outside code and one code refactoring

---

Tests/Controllers/PostControllers/createPost.test.js

Changed the url in the create post "photos" to an existing one

Changed photo url

---

Controllers/MembersControllers/FollowMember.js
Controllers/MembersControllers/GetMember.js

- followMember returns error message instead of "invalid username" if status 400, since the error could have another cause.
- Changed up GetMember quite a bit, it now returns user posts for all possible outcomes, together with a message in case of "not following" or "got no posts". Client arranges which is displayed.

Profile follow

---

Controllers/MembersControllers/FollowMember.js
Controllers/MembersControllers/GetMember.js
Controllers/MembersControllers/ProfilePic.js
Routes/Membersroute.js

- Created route for changing profile pictures
- Change profile picture controller base code, not finished. Had to push for mergin issues.

Own profile

---

Controllers/MembersControllers/GetMembers.js

Now the memberspage doesnt show your own profile.

Filterd out yourown username from object

---

Controllers/Authenticationcontrollers/Login.js

Changed error messages

---

Controllers/PostControllers/likePost.js
Controllers/ProfileControllers/userProfile.js
Database/Database.js

Removed console.logs and unnecessary comments from the code.

Cleaned Database.js 

---

Controllers/MembersControllers/ProfilePic.js
Validations/newProfilePicValidation.js

- Created endpoint for changing your profile picture
- Created validation schema for profile-pic-change fetch

Own profile top card

---

Controllers/MembersControllers/GetMember.js

Prettier changed several lines, and removed a bunch of old code comments.

Removed a few comments and commented code, refactoring.

---

Controllers/Authenticationcontrollers/Login.js

Put back find and toArray to resolve server error

Put back find and toArray to resolve server error

---

Controllers/Authenticationcontrollers/Login.js
Controllers/Authenticationcontrollers/Register.js

- Changed error response to text message

Added 500 error response message

---

Controllers/Authenticationcontrollers/Login.js
Controllers/Authenticationcontrollers/Register.js

-  Changed res.send to res.json at validation error

Error response
